### PR TITLE
Group logging

### PR DESCRIPTION
**Pull request by IAMVANN**
Logs potential group creation and actual group creation details such as the ta involved, the students + their issues, and the original main session.

### CODE REVIEW

**Comment by markfloryan** [comment]
Question: Why are we changing the init.sql file to some other file in this PR? Is there a good reason for this? Could break other people's dev environments. 

@deternitydx @IAMVANN

**Comment by IAMVANN** [comment]
I don't remember consciously changing up the docker file here, and seeing that it's poinit.sqlstgres/ instead of postgres/init.sql, I must've misclicked somewhere and changed up the file name? Not totally sure what happened, but it was unintentional, will change it right now.

**Comment by IAMVANN** [comment]
Just fixed it, it still shows the dockerfile was changed, but its back to "COPY ./backend/docker/postgres/init.sql /docker-entrypoint-initdb.d"

**Comment by markfloryan** [comment]
Thanks for changing that (also...why are you awake haha!?). @deternitydx this looks good to me now, are you ok with merging it?

**Comment by IAMVANN** [comment]
Was doing some leetcode lol

**Comment by deternitydx** [comment]
I'll trust you @markfloryan.  Thanks @IAMVANN

**Review by markfloryan — APPROVED** [review]

**Pull request merged**
